package org.scalajs.dom.raw

class HTMLHeadElement extends HTMLElement("head")
class HTMLMetaElement extends HTMLElement("meta")
class HTMLTitleElement extends HTMLElement("title")
class HTMLLinkElement extends HTMLElement("link")
class HTMLScriptElement extends HTMLElement("script")
class HTMLBodyElement extends HTMLElement("body")
class HTMLHeadingElement extends HTMLElement("h1")
class HTMLDivElement extends HTMLElement("div")
class HTMLSpanElement extends HTMLElement("span")
class HTMLParagraphElement extends HTMLElement("p")
class HTMLAnchorElement extends HTMLElement("a")
class HTMLUListElement extends HTMLElement("ul")
class HTMLLIElement extends HTMLElement("li")
class HTMLFormElement extends HTMLElement("form")
class HTMLLabelElement extends HTMLElement("label")
class HTMLInputElement extends HTMLElement("input")
class HTMLButtonElement extends HTMLElement("button")